name: "Default actions"
description: "Execute the default CI actions for the project"
author: "antonpaa@github.com"

inputs:
  PROJECT_NAME:
    description: "Name of the project"
    required: true
    default: "none"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "code"
  color: "blue"